services:
  api_flask:
    build: .
    container_name: lucasdaniellopes/casadosdados-api:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    command: flask run --host=0.0.0.0
