services:
  api_flask:
    image: lucasdaniellopes/casadosdados-api:latest
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    command: flask run --host=0.0.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.casadosdados.rule=Host(seu_dominio_aqui)"
      - "traefik.http.routers.casadosdados.entrypoints=websecure"
      - "traefik.http.routers.casadosdados.tls.certresolver=myresolver"
      - "traefik.http.services.casadosdados.loadbalancer.server.port=5000"
    networks:
      - sua_network_aqui
networks:
  sua_network_aqui:
    external: true
